apiVersion: v1
kind: Pod
metadata:
  name: dind
  namespace: devops-tools
spec:
  containers:
    - name: gcloud-builder
      image: abhishekf5/maven-abhishek-docker-agent:v1
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock

